version: "3.9"
services:
  chatbot:
    image: chatbotbak:latest
    network_mode: host
#    networks:
#      - omsnet
#    ports:
#      - 9040:80
    deploy:
      mode: replicated
      replicas: 1    
      update_config:
        parallelism: 1
        delay: 1s
        order: start-first
      restart_policy:
        condition: any
        delay: 1s
        window: 2s
#      resources:
#        reservations:
#          devices:
#            - driver: nvidia
#              count: 1
#              capabilities: [gpu]

#networks:
# omsnet:
#    external:
#      name: omsnet
